name: "[Entire] Build Developer Version"

on:
  workflow_dispatch:
  schedule:
    - cron: "15 0 * * *" # 每天 08:15 UTC+8 自动构建

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  delete_current_releases:
    name: Delete Current Releases
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.repository, 'libnyanpasu') }}
    uses: ./.github/workflows/deps-delete-releases.yaml
    with:
      tag: "pre-release"

  windows_amd64_build:
    name: Windows x86_64 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      fixed-webview: false
      arch: "x86_64"
      tag: "pre-release"
    secrets: inherit

  windows_amd64_build_fixed_webview:
    name: Windows x86_64 Build with Fixed WebView
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    needs: [delete_current_releases]
    with:
      portable: true
      nightly: true
      arch: "x86_64"
      fixed-webview: true
      tag: "pre-release"
    secrets: inherit

  update_tag:
    name: Update tag
    needs:
      [
        windows_amd64_build,
        windows_amd64_build_fixed_webview,
      ]
    uses: ./.github/workflows/deps-update-tag.yaml
    with:
      tag: "pre-release"

  updater:
    name: Create Updater
    needs: [update_tag]
    uses: ./.github/workflows/deps-create-updater.yaml
    with:
      nightly: true

  telegram:
    name: Send Release Message to Telegram
    if: startsWith(github.repository, 'libnyanpasu')
    needs: [update_tag]
    uses: ./.github/workflows/deps-message-telegram.yaml
    with:
      nightly: true
    secrets: inherit
